name: Execution Flow
on:
    # push:
    #     branches: [main]
    workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Cache dependencies
              id: cache
              uses: actions/cache@v4
              with:
                path: node_modules
                key: ${{ runner.os }}-node-modules-cache-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-node-modules-cache-

            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Lint Code
              run: npm run lint

    test:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Cache dependencies
              id: cache
              uses: actions/cache@v4
              with:
                path: node_modules
                key: ${{ runner.os }}-node-modules-cache-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-node-modules-cache-

            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Test Code
              id: test-code
              run: npm run test

            - name: Upload test results
              if: failure() && steps.test-code.outcome == 'failure'
              uses: actions/upload-artifact@v4
              with:
                name: test-results
                path: test-results.json

    build:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Cache dependencies
              id: cache
              uses: actions/cache@v4
              with:
                path: node_modules
                key: ${{ runner.os }}-node-modules-cache-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-node-modules-cache-

            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci

            - name: Build Site
              id: build-website
              run: |
                npm run build
                echo "Build completed"
            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: website-artifacts
                path: dist

    deploy:
        runs-on: ubuntu-latest
        needs: [lint, test, build]
        steps:
            - name: Deploy
              run: echo "Deploying..."
            - name: Download Artifacts
              uses: actions/download-artifact@v4
              with:
                name: website-artifacts
                path: dist
            - name: Output Artifacts
              run: ls -l

            - name: Deploy to server
              run: |
                echo "Deploying to server..."

    report:
        needs: [lint, deploy]
        if: failure()
        runs-on: ubuntu-latest
        steps:
            - name: Output Information
              run: |
                echo "Build completed"
                echo "Lint completed"
                echo "Test completed"
                echo "Deploy completed"
                echo "${{ toJson(github)}}"




                  
