name: Matrix Flow
on:
    push:

jobs:
    build:
        strategy:
            matrix:
                node: [12,14,16,18]
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: SetUp Node ${{ matrix.node }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node }}

            - name: Install dependencies
              run: npm ci

            - name: Build Site
              run: npm run build

    
    
